### ISSUE TITLE
Can't import textures in Sweet Home 7.0.2

### ISSUE THREAD

**Issue by dszymczuk** [fabien-michel/sweethome3d-textures-ambientcg#1]
I can't import textures for Sweet Home 7.0.2. I've tried 1024, 512 and 256 version. System is MacOS 12.6.3.

I have information about successfully import
![Zrzut ekranu 2023-03-3 o 14 20 49](https://user-images.githubusercontent.com/539352/222730622-c0ddfb18-e490-40ff-a7b0-39e993d24941.png)

but I can't see on list.

![Zrzut ekranu 2023-03-3 o 14 20 58](https://user-images.githubusercontent.com/539352/222730615-f57481fd-d6d6-47a0-a89d-e8b8d07a9f15.png)

**Comment by fabien-michel** [comment]
Ok, I will have a look at it. The problem already occurred to me, I thought it was fixed.
It must be the zip file not compatible with SweetHome3D.
As a workaround you can try to unzip the .sh3t file (yes it is just a zip file) then re-zip it with your own zip software (then rename it to .sh3t). Maybe the new one will be better handled by SweetHome3D.

You can also just unzip the sh3t file in the SweetHome3D textures folder (don't know where it is on mac)

**Comment by fabien-michel** [comment]
Should be fixed in the latest version.
Thanks for the report

**Comment by dszymczuk** [comment]
Confirm.
Now it works. Thank you!
