### ISSUE TITLE
URLs murena broken

### ISSUE THREAD

**Issue by iwelch** [fabien-michel/sweethome3d-textures-ambientcg#3]
`https://murena.io/s/zMTWK4NA9ezqBYW` is broken.  :-(

thus, I may need to run the script myself.  alas, not being a python user, the instructions are not detailed enough.  I could figure out what a virtual environment is, and managed to install pipx (via pip3).  alas, the `poetry install` tells me `Poetry could not find a pyproject.toml file in /Users/home/test or its parents`.

**Comment by fabien-michel** [comment]
You have to be in the project directory when you run `poetry install`.
I did a mistake in README, you don't have to make a virtual env because poetry will create one for you. (except if you want to install poetry outside your OS)

**Comment by iwelch** [comment]
hi michel --- I tried connecting to ~/test/ and ~/test/textures, but still always the same problem.  this is because I know nothing about the python tooling.

would it be possible to repost the binaries somewhere, at least the 25MB one?

**Comment by fabien-michel** [comment]
I don't know what are the directories ~/test/ and ~/test/textures you are talking about. Should be as simple as :
```
$ git clone https://github.com/fabien-michel/sweethome3d-textures-ambientcg.git
Cloning into 'sweethome3d-textures-ambientcg'...
remote: Enumerating objects: 396, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 396 (delta 19), reused 18 (delta 18), pack-reused 376 (from 1)
Receiving objects: 100% (396/396), 19.28 MiB | 1.17 MiB/s, done.
Resolving deltas: 100% (127/127), done.

$ cd sweethome3d-textures-ambientcg

sweethome3d-textures-ambientcg$ poetry install
Creating virtualenv sweethome3d-textures-ambientcg-LlOF9D26-py3.12 in /xxx
Installing dependencies from lock file

Package operations: 33 installs, 0 updates, 0 removals

  - Installing six (1.16.0)
  - Installing asttokens (2.2.1)
  - Installing executing (1.2.0)
  - Installing parso (0.8.3)
  - Installing ptyprocess (0.7.0)
  - Installing pure-eval (0.2.2)
  - Installing traitlets (5.9.0)
  - Installing wcwidth (0.2.6)
  - Installing attrs (23.1.0)
  - Installing backcall (0.2.0)
  - Installing certifi (2023.5.7)
  - Installing charset-normalizer (3.2.0)
  - Installing decorator (5.1.1)
  - Installing idna (3.4)
  - Installing jedi (0.18.2)
  - Installing matplotlib-inline (0.1.6)
  - Installing pexpect (4.8.0)
  - Installing pickleshare (0.7.5)
  - Installing prompt-toolkit (3.0.39)
  - Installing pygments (2.15.1)
  - Installing stack-data (0.6.2)
  - Installing urllib3 (2.0.3)
  - Installing cattrs (23.1.2)
  - Installing ipython (8.14.0)
  - Installing markupsafe (2.1.3)
  - Installing platformdirs (3.9.1)
  - Installing requests (2.31.0)
  - Installing url-normalize (1.4.3)
  - Installing ipdb (0.13.13)
  - Installing jinja2 (3.1.2)
  - Installing pillow (10.0.0)
  - Installing requests-cache (1.1.0)
  - Installing tomlkit (0.11.8)

sweethome3d-textures-ambientcg$ poetry run python build.py
...```

**Comment by fabien-michel** [comment]
Murena.io drive has huge outage, seems they do not plan a drive restoration before few days. I will try to find another provider
https://community.e.foundation/t/update-on-murena-io-service-outage/61781

**Comment by iwelch** [comment]
if you want me to host it for a few weeks on a fast site, I could.  but I would think a free dropbox or google drive would do the job just fine.

**Comment by iwelch** [comment]
* poetry does not come with python, so it needs to be installed first, too.  on macos, this is achievable by `brew install poetry`.

* following your instructions:

```
$ poetry install
...

  - Installing pillow (10.0.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/poetry/1.8.4/libexec/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "/opt/homebrew/Cellar/poetry/1.8.4/libexec/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/poetry/1.8.4/libexec/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/ss/8fxl2z314jxg69sqfqd4j9840000gn/T/tmp73bv4w96/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/ss/8fxl2z314jxg69sqfqd4j9840000gn/T/tmp73bv4w96/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "/private/var/folders/ss/8fxl2z314jxg69sqfqd4j9840000gn/T/tmp73bv4w96/.venv/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 30, in <module>
    File "<string>", line 27, in get_version
  KeyError: '__version__'
  

  at /opt/homebrew/Cellar/poetry/1.8.4/libexec/lib/python3.13/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pillow (10.0.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pillow (==10.0.0)"'.

```

**Comment by mrigne** [comment]
Faced with same problem. To successfully run this tool I did next steps:
1. Follow this instruction, but use 3.11.0 version instead of 3.10.0 - [stackoverflow answer](https://stackoverflow.com/a/77935901)
2. edit build.py file:
execute in terminal `nano build.py`
Press Control + W
type 'remove' and press enter - it should find row with remove_expired_responses
just delete this line, press Control + O and press enter
3. run `poetry run python build.py`
4. Enjoy!

I have generated files and uploaded to media fire:
[256](https://www.mediafire.com/file/4tjgupiihrfedf7/ambientcg_256.sh3t/file)
[512](https://www.mediafire.com/file/kubuvdy5jvkz6ha/ambientcg_512.sh3t/file)
[1024](https://www.mediafire.com/file/j7x81hdod4ihbqh/ambientcg_1024.sh3t/file)

Also I have added alt links on mega.co.nz:
[256](https://mega.nz/file/bZ1FSTQb#0RtGDETe9X5xe1hMMX8OpXQOiJ7noS9H7MY3d26xQtM)
[512](https://mega.nz/file/nM0GWCgJ#4Hr5Son6JN15Pmi3zTtN0iyag8JKdl_HudseCCco4LI)
[1024](https://mega.nz/file/3ZFjkCSY#5jCXcS2EgCKstGbjn2yu8JVToaMJqE9igJxdZp6179k)

**Comment by nitewing76** [comment]
I'm getting these errors:

Randomly a few times (more than twice): 

![ScreenShot_20241220093319](https://github.com/user-attachments/assets/fb03e987-0dcb-4b98-915c-cd540a118f04)

![ScreenShot_20241220093319](https://github.com/user-attachments/assets/71e1c686-c744-4c8f-94b0-fcf092697ed9)


And at the end: 

![ScreenShot_20241220093733](https://github.com/user-attachments/assets/73b03c77-66be-4997-8b28-9d361ebc3852)

**Comment by mrigne** [comment]
At first screenshot there are warnings, not errors. 
faced with same issue as you show in second screenshot - it is preview generation part - files should be generated successfully

**Comment by fabien-michel** [comment]
New version released, files are now stored on google drive.
@mrigne can't reproduce DecompressionBombWarning, but I made a change which I hope should avoid it. Font DejaVue is now embed with the project.
